### ISSUE TITLE
JS to CSS

### ISSUE THREAD

**Issue by rotimi-best** [loklaan/convert-css-js-app#8]
This is a really cool app. I do have a use case of wanting to convert my JS code into CSS.

Do you plan on adding this to this? or I can fork this repo and build this feature on top of it?

**Comment by rotimi-best** [comment]
I just discovered looking into the code that I could edit both sides. I just wasn't obvious to me that I could edit what was on the right hand side. Being a constant user of google translate you get used to the fact that the right side pane is view only while the left is for editing.

A possible feature to add is to make the right hand pane un editable and then allow the user toggle the `<Arrows />`, which therefore changes the position from `css - js` to `js - css` and vice versa

**Comment by loklaan** [comment]
@rotimi-best Yeah I agree the UX there is a bit sketch. I'd be 100% open to a PR to improve the UI 👍
